name: pdftoreel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
flutter:
    sdk: flutter
    # State management
    flutter_riverpod: ^2.5.1 
    # Navigace a utility
    go_router: ^13.2.0
    dio: ^5.4.1 # Pro HTTP požadavky
    intl: ^0.19.0 # Pro formátování dat a jazyky

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
