// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLsof3EAdQE21iwb-3q7Bz5y1f6cNlkds',
    appId: '1:600901568590:web:5953aaf6b9822bb87fdb1f',
    messagingSenderId: '600901568590',
    projectId: 'pdf-to-reel-auth',
    authDomain: 'pdf-to-reel-auth.firebaseapp.com',
    storageBucket: 'pdf-to-reel-auth.firebasestorage.app',
    measurementId: 'G-509LLRG5G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEKpX7Exnyl8mFFQwkyfNWP46DOOlHHZA',
    appId: '1:600901568590:android:3974c374a9d0447f7fdb1f',
    messagingSenderId: '600901568590',
    projectId: 'pdf-to-reel-auth',
    storageBucket: 'pdf-to-reel-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvtVewhaP43aK2vR2Z00Tf62HM3V5vV3s',
    appId: '1:600901568590:ios:e012a38be1273ac07fdb1f',
    messagingSenderId: '600901568590',
    projectId: 'pdf-to-reel-auth',
    storageBucket: 'pdf-to-reel-auth.firebasestorage.app',
    iosClientId: '600901568590-aosmp83ia5vhnedff0pu56adkcv36km5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdftoreel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvtVewhaP43aK2vR2Z00Tf62HM3V5vV3s',
    appId: '1:600901568590:ios:e012a38be1273ac07fdb1f',
    messagingSenderId: '600901568590',
    projectId: 'pdf-to-reel-auth',
    storageBucket: 'pdf-to-reel-auth.firebasestorage.app',
    iosClientId: '600901568590-aosmp83ia5vhnedff0pu56adkcv36km5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdftoreel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLsof3EAdQE21iwb-3q7Bz5y1f6cNlkds',
    appId: '1:600901568590:web:5953aaf6b9822bb87fdb1f',
    messagingSenderId: '600901568590',
    projectId: 'pdf-to-reel-auth',
    authDomain: 'pdf-to-reel-auth.firebaseapp.com',
    storageBucket: 'pdf-to-reel-auth.firebasestorage.app',
    measurementId: 'G-509LLRG5G4',
  );

}